const texts = {
    pl: {
        tasks: 'Zadania',
        profile: 'Profil',
        note: 'Notatnik',
        notes: 'Notatki',
        addNote: 'Dodaj notatkę',
        editNote: 'Edytuj notatkę',
        deleteNote: 'Usuń notatkę',
        noteTitle: 'Tytuł notatki',
        noteContent: 'Treść notatki',
        noteStatus: 'Status notatki',
        noteImportant: 'Ważne',
        noteDone: 'Wykonane',
        saveNote: 'Zapisz notatkę',
        cancel: 'Anuluj',
        confirmDelete: 'Czy na pewno chcesz usunąć tę notatkę?',
        logout: 'Wyloguj się',
        login: 'Zaloguj się',
        loginPage: 'Logowanie',
        register: 'Zarejestruj się',
        switchLanguage: 'Zmień język:',
        error: 'Niewypełniono wszystkich pól',
        invalidCredentials: 'Nieprawidłowe dane logowania',
        loginError: 'Błąd logowania. Spróbuj ponownie później.',
        registerSuccess: 'Rejestracja udana',
        profileUpdated: 'Profil zaktualizowany pomyślnie',
        welcome: 'Wszystko w jednej aplikacji, dla efektywnej pracy',
        welcomeDescription: 'Zarządzaj wszystkim w jednym miejscu, dostosowanym do każdego rodzaju pracy.',
        accountNotActivated: 'Konto nie jest aktywowane. Wyślij ponownie <a href="#" id="resend-link">link aktywacyjny</a>',
        userNotFound: 'Użytkownik nie został znaleziony',
        accountActivation: 'Aktywacja konta',
        activationInfoMessage: 'Twoje konto zostało zarejestrowane. Sprawdź swoją skrzynkę pocztową, aby aktywować konto.',
        activationErrorMessage: 'Aktywacja nie powiodła się. Spróbuj ponownie później.',
        username: 'Nazwa użytkownika',
        email: 'Email',
        password: 'Hasło',
        confirmPassword: 'Potwierdź hasło',
        fillAllFields: 'Proszę wypełnić wszystkie pola formularza',
        validEmail: 'Proszę podać prawidłowy adres email',
        passwordLength: 'Hasło powinno mieć co najmniej 8 znaków',
        passwordSpecialChars: 'Hasło powinno zawierać co najmniej jeden znak specjalny',
        passwordMismatch: 'Potwierdzenie hasła nie pasuje',
        emailExists: 'Ten email jest już zarejestrowany',
        usernameExists: 'Ta nazwa użytkownika jest już zajęta',
        registrationError: 'Błąd podczas rejestracji. Spróbuj ponownie później.',
        rateLimitExceeded: 'Zbyt wiele prób logowania. Spróbuj ponownie za 15 minut.',
        show: 'Pokaż',
        hide: 'Ukryj',
        tasksTodo: 'Do zrobienia',
        tasksInProgress: 'W trakcie',
        tasksDone: 'Gotowe',
        addTask: 'Dodaj zadanie',
        delete: 'Usuń',
        taskTitle: 'Tytuł zadania',
        taskDescription: 'Opis zadania',
        userProfile: 'Profil użytkownika',
        update: 'Aktualizuj',
        loading: 'Ładowanie...',
        addTaskError: 'Błąd dodawania zadania. Spróbuj ponownie później.',
        deleteTask: 'Usuń zadanie',
        languagePolish: 'Polski',
        languageEnglish: 'English',
        languageGerman: 'Deutsch',
        registration: 'Rejestracja',
        activationLinkResent: 'Nowy link aktywacyjny został wysłany na twój email.',
        activationLinkError: 'Błąd wysyłania linku aktywacyjnego. Spróbuj ponownie później.',
        showPassword: 'Pokaż hasło',
        forgotPassword: 'Zapomniałeś hasła?',
        resetPassword: 'Zresetuj hasło',
        newPassword: 'Nowe hasło',
        sendResetLink: 'Wyślij link do resetowania hasła',
        resetLinkSent: 'Link do resetowania hasła został wysłany na Twój email.',
        resetLinkError: 'Błąd wysyłania linku resetującego. Spróbuj ponownie później.',
        passwordResetSuccess: 'Hasło zostało pomyślnie zresetowane. Przekierowanie na stronę logowania...',
        resetPasswordError: 'Błąd resetowania hasła. Spróbuj ponownie później.',
        cookieBanner: {
            message: 'Nasza strona używa ciasteczek, aby zapewnić Ci najlepszą jakość usług. Kontynuując korzystanie z naszej strony, wyrażasz zgodę na używanie ciasteczek.',
            accept: 'Akceptuję'
        }
    },
    en: {
        tasks: 'Tasks',
        profile: 'Profile',
        note: 'Notebook',
        notes: 'Notes',
        addNote: 'Add Note',
        editNote: 'Edit Note',
        deleteNote: 'Delete Note',
        noteTitle: 'Note Title',
        noteContent: 'Note Content',
        noteStatus: 'Note Status',
        noteImportant: 'Important',
        noteDone: 'Done',
        saveNote: 'Save Note',
        cancel: 'Cancel',
        confirmDelete: 'Are you sure you want to delete this note?',
        logout: 'Logout',
        login: 'Login',
        loginPage: 'Sign in',
        register: 'Register',
        switchLanguage: 'Switch language:',
        error: 'Please fill in all fields',
        invalidCredentials: 'Invalid credentials',
        loginError: 'Login error. Please try again later.',
        registerSuccess: 'Registration successful',
        profileUpdated: 'Profile updated successfully',
        welcome: 'The everything app, for effective work',
        welcomeDescription: 'Manage everything in one place, tailored for any type of work.',
        accountNotActivated: 'Account is not activated. Resend <a href="#" id="resend-link">activation link</a>',
        userNotFound: 'User not found',
        accountActivation: 'Account Activation',
        activationInfoMessage: 'Your account has been registered. Please check your email to activate your account.',
        activationErrorMessage: 'Activation failed. Please try again later.',
        username: 'Username',
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        fillAllFields: 'Please fill in all form fields',
        validEmail: 'Please enter a valid email address',
        passwordLength: 'Password should be at least 8 characters long',
        passwordSpecialChars: 'Password should contain at least one special character',
        passwordMismatch: 'Password confirmation does not match',
        emailExists: 'This email is already registered',
        usernameExists: 'This username is already taken',
        registrationError: 'Error during registration. Please try again later.',
        rateLimitExceeded: 'Too many login attempts from this IP, please try again after 15 minutes.',
        show: 'Show',
        hide: 'Hide',
        tasksTodo: 'To Do',
        tasksInProgress: 'In Progress',
        tasksDone: 'Done',
        addTask: 'Add Task',
        delete: 'Delete',
        taskTitle: 'Task Title',
        taskDescription: 'Task Description',
        userProfile: 'User Profile',
        update: 'Update',
        loading: 'Loading...',
        addTaskError: 'Error adding task. Please try again later.',
        deleteTask: 'Delete Task',
        languagePolish: 'Polski',
        languageEnglish: 'English',
        languageGerman: 'Deutsch',
        registration: 'Registration',
        activationLinkResent: 'A new activation link has been sent to your email.',
        activationLinkError: 'Error sending activation link. Please try again later.',
        showPassword: 'Show password',
        forgotPassword: 'Forgot Password?',
        resetPassword: 'Reset Password',
        newPassword: 'New Password',
        sendResetLink: 'Send Reset Link',
        resetLinkSent: 'A password reset link has been sent to your email.',
        resetLinkError: 'Error sending reset link. Please try again later.',
        passwordResetSuccess: 'Password reset successfully. Redirecting to login page...',
        resetPasswordError: 'Error resetting password. Please try again later.',
        cookieBanner: {
            message: 'Our site uses cookies to ensure you get the best experience. By continuing to use our site, you consent to our use of cookies.',
            accept: 'I Accept'
        }
    },
    de: {
        tasks: 'Aufgaben',
        profile: 'Profil',
        note: 'Notizbuch',
        notes: 'Notizen',
        addNote: 'Notiz hinzufügen',
        editNote: 'Notiz bearbeiten',
        deleteNote: 'Notiz löschen',
        noteTitle: 'Notiztitel',
        noteContent: 'Notizinhalte',
        noteStatus: 'Notizstatus',
        noteImportant: 'Wichtig',
        noteDone: 'Erledigt',
        saveNote: 'Notiz speichern',
        cancel: 'Abbrechen',
        confirmDelete: 'Möchten Sie diese Notiz wirklich löschen?',
        logout: 'Ausloggen',
        login: 'Anmelden',
        loginPage: 'Anmeldeseite',
        register: 'Registrieren',
        switchLanguage: 'Sprache wechseln:',
        error: 'Bitte füllen Sie alle Felder aus',
        invalidCredentials: 'Ungültige Anmeldeinformationen',
        loginError: 'Anmeldefehler. Bitte versuchen Sie es später erneut.',
        registerSuccess: 'Registrierung erfolgreich',
        profileUpdated: 'Profil erfolgreich aktualisiert',
        welcome: 'Alles in einer App, für effektive Arbeit',
        welcomeDescription: 'Verwalten Sie alles an einem Ort, maßgeschneidert für jede Art von Arbeit.',
        accountNotActivated: 'Konto ist nicht aktiviert. Erneut senden <a href="#" id="resend-link">Aktivierungslink</a>',
        userNotFound: 'Benutzer nicht gefunden',
        accountActivation: 'Kontoaktivierung',
        activationInfoMessage: 'Ihr Konto wurde registriert. Bitte überprüfen Sie Ihre E-Mail, um Ihr Konto zu aktivieren.',
        activationErrorMessage: 'Die Aktivierung ist fehlgeschlagen. Bitte versuchen Sie es später erneut.',
        username: 'Benutzername',
        email: 'E-Mail',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        fillAllFields: 'Bitte füllen Sie alle Formularfelder aus',
        validEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
        passwordLength: 'Das Passwort sollte mindestens 8 Zeichen lang sein',
        passwordSpecialChars: 'Das Passwort sollte mindestens ein Sonderzeichen enthalten',
        passwordMismatch: 'Die Passwortbestätigung stimmt nicht überein',
        emailExists: 'Diese E-Mail ist bereits registriert',
        usernameExists: 'Dieser Benutzername ist bereits vergeben',
        registrationError: 'Fehler bei der Registrierung. Bitte versuchen Sie es später erneut.',
        rateLimitExceeded: 'Zu viele Anmeldeversuche von dieser IP, bitte versuchen Sie es nach 15 Minuten erneut.',
        show: 'Zeigen',
        hide: 'Verbergen',
        tasksTodo: 'Zu erledigen',
        tasksInProgress: 'In Bearbeitung',
        tasksDone: 'Erledigt',
        addTask: 'Aufgabe hinzufügen',
        delete: 'Löschen',
        taskTitle: 'Aufgabentitel',
        taskDescription: 'Aufgabenbeschreibung',
        userProfile: 'Benutzerprofil',
        update: 'Aktualisieren',
        loading: 'Wird geladen...',
        addTaskError: 'Fehler beim Hinzufügen der Aufgabe. Bitte versuchen Sie es später erneut.',
        deleteTask: 'Aufgabe löschen',
        languagePolish: 'Polski',
        languageEnglish: 'English',
        languageGerman: 'Deutsch',
        registration: 'Registrierung',
        activationLinkResent: 'Ein neuer Aktivierungslink wurde an Ihre E-Mail gesendet.',
        activationLinkError: 'Fehler beim Senden des Aktivierungslinks. Bitte versuchen Sie es später erneut.',
        showPassword: 'Passwort anzeigen',
        forgotPassword: 'Passwort vergessen?',
        resetPassword: 'Passwort zurücksetzen',
        newPassword: 'Neues Passwort',
        sendResetLink: 'Link zum Zurücksetzen senden',
        resetLinkSent: 'Ein Link zum Zurücksetzen des Passworts wurde an Ihre E-Mail gesendet.',
        resetLinkError: 'Fehler beim Senden des Zurücksetzungslinks. Bitte versuchen Sie es später erneut.',
        passwordResetSuccess: 'Passwort erfolgreich zurückgesetzt. Weiterleitung zur Anmeldeseite...',
        resetPasswordError: 'Fehler beim Zurücksetzen des Passworts. Bitte versuchen Sie es später erneut.',
        cookieBanner: {
            message: 'Unsere Website verwendet Cookies, um sicherzustellen, dass Sie die beste Erfahrung machen. Indem Sie unsere Website weiterhin nutzen, stimmen Sie der Verwendung von Cookies zu.',
            accept: 'Akzeptieren'
        }
    }
};

export default texts;