const texts = {
    pl: {
        tasks: 'Zadania',
        profile: 'Profil',
        logout: 'Wyloguj się',
        login: 'Zaloguj',
        register: 'Zarejestruj się',
        switchLanguage: 'Zmień język:',
        error: 'Błąd',
        invalidCredentials: 'Nieprawidłowe dane logowania',
        loginError: 'Błąd logowania. Spróbuj ponownie później.',
        registerSuccess: 'Rejestracja udana',
        profileUpdated: 'Profil zaktualizowany pomyślnie',
        welcome: 'Wszystko w jednej aplikacji, dla efektywnej pracy',
        welcomeDescription: 'Zarządzaj wszystkim w jednym miejscu, dostosowanym do każdego rodzaju pracy.',
        accountNotActivated: 'Konto nie jest aktywowane. Sprawdź swój email, aby aktywować konto.',
        userNotFound: 'Użytkownik nie został znaleziony',
    },
    en: {
        tasks: 'Tasks',
        profile: 'Profile',
        logout: 'Logout',
        login: 'Login',
        register: 'Register',
        switchLanguage: 'Switch language:',
        error: 'Error',
        invalidCredentials: 'Invalid credentials',
        loginError: 'Login error. Please try again later.',
        registerSuccess: 'Registration successful',
        profileUpdated: 'Profile updated successfully',
        welcome: 'The everything app, for effective work',
        welcomeDescription: 'Manage everything in one place, tailored for any type of work.',
        accountNotActivated: 'Account is not activated. Please check your email for activation link.',
        userNotFound: 'User not found',
    },
    de: {
        tasks: 'Aufgaben',
        profile: 'Profil',
        logout: 'Ausloggen',
        login: 'Anmelden',
        register: 'Registrieren',
        switchLanguage: 'Sprache wechseln:',
        error: 'Fehler',
        invalidCredentials: 'Ungültige Anmeldeinformationen',
        loginError: 'Anmeldefehler. Bitte versuchen Sie es später erneut.',
        registerSuccess: 'Registrierung erfolgreich',
        profileUpdated: 'Profil erfolgreich aktualisiert',
        welcome: 'Alles in einer App, für effektive Arbeit',
        welcomeDescription: 'Verwalten Sie alles an einem Ort, maßgeschneidert für jede Art von Arbeit.',
        accountNotActivated: 'Konto ist nicht aktiviert. Bitte überprüfen Sie Ihre E-Mail für den Aktivierungslink.',
        userNotFound: 'Benutzer nicht gefunden',
    },
};

export default texts;
